pcm.null_device {
    type null
}

pcm.audio_out {
    type plug
    slave.pcm {
        type multi
        slaves {
            output      { channels 2 pcm "null_device" }  #hw:Loopback,0,2
            snapcast    { channels 2 pcm "hw:Loopback,0,1" }
        }
        bindings {
            0 { slave output channel 0 }
            1 { slave output channel 1 }
            2 { slave snapcast channel 0 }
            3 { slave snapcast channel 1 }
        }
    }
    ttable [
        [ 1 0 0 0 ]   # Input L → DAC L only
        [ 0 1 0 0 ]   # Input R → DAC R only
        [ 0 0 1 0 ]   # Input L → Loopback L only
        [ 0 0 0 1 ]   # Input R → Loopback R only
    ]
}

