pcm.audio_out {
    type plug
    slave.pcm {
        type multi
        slaves {
            output      { channels 2 pcm "null_device" } 
            snapcast    { channels 2 pcm "hw:Loopback,0,1" }
            spectrum    { channels 2 pcm "hw:Loopback,0,2" }
        }
        bindings {
            0 { slave output channel 0 }
            1 { slave output channel 1 }
            2 { slave snapcast channel 0 }
            3 { slave snapcast channel 1 }
            4 { slave spectrum channel 0 }
            5 { slave spectrum channel 1 }
        }
    }
    ttable [
        [ 1 0 0 0 0 0]   # Input L → DAC L only
	[ 0 1 0 0 0 0]   # Input R → DAC R only
	[ 0 0 1 0 0 0]   # Input L → Snapcast L only
	[ 0 0 0 1 0 0]   # Input R → Snapcast R only
	[ 0 0 0 0 1 0]   # Input L → Spectrum L only
	[ 0 0 0 0 0 1]   # Input R → Spectrum R only
    ]
}

