[global]
workgroup = WORKGROUP
server string = Python SMB
security = user
map to guest = bad user
dns proxy = no
log level = 0

[Internal]
path = /home/pi/Internal
comment = 
browseable = yes
read only = no
guest ok = yes
force user = pi
create mask = 0664
directory mask = 0775

